import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  count: 0,
};

const counterSlice = createSlice({
  name: "counter",
  initialState,
  reducers: {
    incrementSlice: (state) => {
      state.count += 1;
    },
    decrementSlice: (state) => {
      state.count -= 1;
    },
    setValueSlice: (state, action) => {
      state.count = action.payload;
    },
  },
});
export const { incrementSlice, decrementSlice, setValueSlice } =
  counterSlice.actions;

// Export reducer generated by createSlice
export default counterSlice.reducer;
